#ifndef __LP_VIEWER_DEFINE_ETHERNET_H__
#define __LP_VIEWER_DEFINE_ETHERNET_H__

// ETHERNET
#define ETHERNET_IP_SERVER				_T("0.0.0.0")
#define ETHERNET_PORT_SERVER			2000

#define	ETHERNET_PORT_GVCP				3956

#define ETHERNET_PORT_STREAM_BASE		50000
#define ETHERNET_PORT_CONTROL_BASE		51000





#endif