#pragma once

#define XML_NAVINODE_ROOT				_T("NAVIROOT")

#define XML_NAVINODE_MODE				_T("TEMPLATEMODE")
#define XML_NAVINODE_NAME				_T("TEMPLATENAME")
#define XML_NAVINODE_CREATEDATE			_T("TEMPLATECREATEDATE")
#define XML_NAVINODE_LASTDATE			_T("TEMPLATELASTMODIFYDATE")
#define XML_NAVINODE_DESC				_T("TEMPLATEDESC")
#define XML_NAVINODE_PROTECT			_T("PROTECTION")
#define XML_NAVINODE_PASSWD				_T("PASSWD")

// Sequence Manager
#define XML_NAVINODE_SEQMANAGER			_T("SEQUENCEMANAGER")
#define XML_NAVINODE_SEQUENCE			_T("SEQUENCE")
#define XML_NAVINODE_APPLICATION		_T("APPLICATION")

#define XML_NAVINODE_APP_SEQINDEX		_T("SEQINDEX")
#define XML_NAVINODE_APP_TYPE			_T("APPTYPE")
#define XML_NAVINODE_APP_INFO			_T("APPINFO")
#define XML_NAVINODE_APP_FILTER			_T("APPFILTER")

#define XML_NAVINODE_APP_PATH			_T("IMGPATH")
#define XML_NAVINODE_APP_NAME			_T("APPNAME")
#define XML_NAVINODE_APP_ROIREF			_T("INDEXROIREF")
#define XML_NAVINODE_APP_ROICOPY		_T("INDEXROICOPY")
#define XML_NAVINODE_APP_SRCIMG			_T("INDEXSRCIMG")

#define XML_NAVINODE_APP_IMAGELIST		_T("IMAGELIST")
#define XML_NAVINODE_APP_BUFFER			_T("BUFFER")
#define XML_NAVINODE_APP_CONFIGLIST		_T("CONFIGLIST")
#define XML_NAVINODE_APP_CONFIG			_T("CONFIG")

#define XML_NAVINODE_ROI_LIST			_T("ROILIST")

#define XML_NAVINODE_ROI_INFO			_T("ROIINFO")
#define XML_NAVINODE_ROI_TYPE			_T("ROITYPE")
#define XML_NAVINODE_ROI_FACE			_T("ROIFACE")
#define XML_NAVINODE_ROI_POSITION		_T("ROIPOS")
#define XML_NAVINODE_ROI_POINTLIST		_T("ROIPOINTLIST")
#define XML_NAVINODE_ROI_POINT			_T("ROIPOINT")
#define XML_NAVINODE_ROI_STEP			_T("STEP")
#define XML_NAVINODE_ROI_OPTION			_T("OPTION")
#define XML_NAVINODE_ROI_RING			_T("ROIRING")
#define XML_NAVINODE_ROI_RANGE			_T("ROIRANGE")
#define XML_NAVINODE_ROI_MASK			_T("ROIMASK")
#define XML_NAVINODE_ROI_CRITERIA		_T("CRITERIA")


// Programming Setting  Node
#define XML_NAVINODE_SET_ROOT				_T("NAVI_PROGRAMSET")

#define XML_NAVINODE_SET_AUTH				_T("AUTH")
#define XML_NAVINODE_SET_USERID				_T("USERID")
#define XML_NAVINODE_SET_PASSWORD			_T("PASSWD")

#define XML_NAVINODE_SET_LICENSEINFO		_T("LICENSEINFO")
#define XML_NAVINODE_SET_LICENSETYPE		_T("LICENSETYPE")
#define XML_NAVINODE_SET_EXPIRATIONDATE		_T("EXPIRATIONDATE")

#define XML_NAVINODE_SET_SETINFO			_T("SETINFO")
#define XML_NAVINODE_SET_INSTALLPATH		_T("INSTALLPATH")
#define XML_NAVINODE_SET_LASTIMAGEPATH		_T("LASTIMAGEPATH")

#define XML_NAVINODE_SET_CONFIGPROJECT		_T("CONFIGRECENTSPROJECT")
#define XML_NAVINODE_SET_INSPECTPROJECT		_T("INSPECTRECENTSPROJECT")
#define XML_NAVINODE_SET_PROJECTPATH		_T("PROJECTPATH")
#define XML_NAVINODE_SET_LASTPROJECT		_T("LASTCLOSEDPROJECT")

#define XML_NAVINODE_SET_TRANSFERDATA		_T("TRANSFERDATA")
#define XML_NAVINODE_SET_SERIAL				_T("SERIAL")
#define XML_NAVINODE_SET_CONFIG				_T("CONFIG")
#define XML_NAVINODE_SET_ETHERNET			_T("ETHERNET")
#define XML_NAVINODE_SET_SERVER				_T("SERVER")
#define XML_NAVINODE_SET_CLIENTLIST			_T("CLIENTLIST")
#define XML_NAVINODE_SET_CLIENT				_T("CLIENT")

#define XML_NAVINODE_SET_LOGGING			_T("LOGGING")
#define XML_NAVINODE_SET_LOGFILE			_T("LOG")
#define XML_NAVINODE_SET_IMAGEFILE			_T("IMAGE")
#define XML_NAVINODE_SET_AUTODELETE			_T("AUTODELETE")
#define XML_NAVINODE_SET_ORIGINALIMG		_T("ORIGINALIMG")
#define XML_NAVINODE_SET_RESULTIMG			_T("RESULTIMG")
#define XML_NAVINODE_SET_PASS				_T("PASS")
#define XML_NAVINODE_SET_FAIL				_T("FAIL")


// Stat Sequence
#define XML_NAVINDE_STAT_ROOT				_T("STATLIST")
#define XML_NAVINDE_STAT_SEQUENCE			_T("SEQUENCE")
#define XML_NAVINDE_STAT_APPLICATION		_T("APPLICATION")
#define XML_NAVINDE_STAT_SEQSTAT			_T("SEQSTAT")
#define XML_NAVINDE_STAT_APPSTAT			_T("APPSTAT")



// Camera Default Information Node
#define XML_CAMERANODE_ROOT					_T("CAMERAROOT")
#define XML_CAMERANODE_GIGE					_T("GIGE")
#define XML_CAMERANODE_USB					_T("USB")
#define XML_CAMERANODE_ETHERNET				_T("ETHERNET")
#define XML_CAMERANODE_CAMERALINK			_T("CAMERALINK")
#define XML_CAMERANODE_CAMERA				_T("CAMERA")
#define XML_CAMERANODE_FRAMEGRABBER			_T("FRAMEGRABBER")
#define XML_CAMERANODE_GRABBER				_T("GRABBER")
#define XML_CAMERANODE_CAMFILE				_T("CAMFILE")
#define XML_CAMERANODE_CAMFILE_ITEM			_T("FILE")

#define XML_CAMERANODE_CAM_DATABITS			_T("DATABITS")
#define XML_CAMERANODE_CAM_BIT				_T("BIT")

#define XML_CAMERANODE_CAM_COLOR			_T("COLOR")
#define XML_CAMERANODE_CAM_COLORFORMAT		_T("COLORFORMAT")
#define XML_CAMERANODE_CAM_PIXELFORMAT		_T("PIXELFORMAT")
#define XML_CAMERANODE_CAM_PIXEL			_T("PIXEL")
#define XML_CAMERANODE_CAM_RGBGAIN			_T("RGBGAIN")

#define XML_CAMERANODE_CAM_MTU				_T("MTU")

#define XML_CAMERANODE_CAM_ROI				_T("ROI")
#define XML_CAMERANODE_CAM_ROI_UNIT			_T("UNIT")
#define XML_CAMERANODE_CAM_ROI_MIN			_T("MIN")

#define XML_CAMERANODE_CAM_GAIN				_T("GAIN")
#define XML_CAMERANODE_CAM_EXPOSURE			_T("EXPOSURE")
#define XML_CAMERANODE_CAM_FRAMERATE		_T("FRAMERATE")

#define XML_CAMERANODE_CAM_TRIGGER			_T("TRIGGER")
#define XML_CAMERANODE_CAM_TRIGGER_MODE		_T("MODE")
#define XML_CAMERANODE_CAM_TRIGGER_SOURCE	_T("SOURCE")
#define XML_CAMERANODE_CAM_TRIGGER_TYPE		_T("TYPE")
#define XML_CAMERANODE_CAM_TRIGGER_POLARITY	_T("POLARITY")
#define XML_CAMERANODE_CAM_TRIGGER_DELAY	_T("DELAY")

#define XML_CAMERANODE_CAM_STROBE			_T("STROBE")
#define XML_CAMERANODE_CAM_STROBE_MODE		_T("MODE")
#define XML_CAMERANODE_CAM_STROBE_SYNC		_T("SYNC")
#define XML_CAMERANODE_CAM_STROBE_POLARITY	_T("POLARITY")
#define XML_CAMERANODE_CAM_STROBE_WIDTH		_T("WIDTH")
#define XML_CAMERANODE_CAM_STROBE_DELAY		_T("DELAY")

#define XML_CAMERANODE_CAM_SYMMETRY			_T("SYMMETRY")

#define XML_CAMERANODE_CAM_LUT				_T("LUT")
#define XML_CAMERANODE_CAM_EFFECT			_T("EFFECT")
#define XML_CAMERANODE_CAM_EFFECT_NR		_T("NR")
#define XML_CAMERANODE_CAM_EFFECT_GC		_T("GC")
#define XML_CAMERANODE_CAM_EFFECT_CM		_T("CM")
#define XML_CAMERANODE_CAM_EFFECT_AWB		_T("AWB")
#define XML_CAMERANODE_CAM_EFFECT_FPN		_T("FPN")
#define XML_CAMERANODE_CAM_EFFECT_PRNU		_T("PRNU")
#define XML_CAMERANODE_CAM_EFFECT_DPC		_T("DPC")
#define XML_CAMERANODE_CAM_EFFECT_SMOTH		_T("SMOTH")
#define XML_CAMERANODE_CAM_EFFECT_SHARPEN	_T("SHARPEN")

#define XML_CAMERANODE_CAM_USERSET			_T("USERSET")

#define XML_CAMERANODE_CAM_STARTUP			_T("STARTUP")
#define XML_CAMERANODE_CAM_INDEX			_T("INDEX")
#define XML_CAMERANODE_CAM_RANGE			_T("RANGE")
#define XML_CAMERANODE_CAM_ITEM				_T("ITEM")

#define XML_CAMERANODE_CLCAM_IMAGETAPS		_T("IMGTAPS")
#define XML_CAMERANODE_CLCAM_TAP			_T("TAP")
#define XML_CAMERANODE_CLCAM_DATABITS		_T("DATABITS")
#define XML_CAMERANODE_CLCAM_BIT			_T("BIT")

// User config
#define XML_USERNODE_ROOT					_T("USERCONFIG")
#define XML_USERNODE_OUTPUTCONFIGLIST		_T("OUTPUTCONFIGLIST")
#define XML_USERNODE_OUTPUTCONFIG			_T("OUTPUTCONFIG")
#define XML_USERNODE_OUTPUTTEXT				_T("OUTPUTTEXT")
#define XML_USERNODE_OUTPUTPEN				_T("OUTPUTPEN")
#define XML_USERNODE_OUTPUTBRUSH			_T("OUTPUTBRUSH")
#define XML_USERNODE_OUTPUTOPTION			_T("OUTPUTOPTION")

// Camera Config
#define XML_CAMERAUSER_NODE_ROOT			_T("CAMERAUSERCONFIG")
#define XML_CAMERAUSER_NODE_COMMON			_T("COMMON")
#define XML_CAMERAUSER_NODE_TIMEOUT			_T("TIMEOUT")
#define XML_CAMERAUSER_NODE_RANGE			_T("RANGE")
#define XML_CAMERAUSER_NODE_MTU				_T("MTU")

// Attribute define
#define XML_NAVI_ATTR_X						_T("x")
#define XML_NAVI_ATTR_Y						_T("y")
#define XML_NAVI_ATTR_W						_T("w")
#define XML_NAVI_ATTR_H						_T("h")
#define XML_NAVI_ATTR_ANGLE					_T("angle")
#define XML_NAVI_ATTR_MODE					_T("mode")
#define XML_NAVI_ATTR_DIRECTION				_T("direction")
#define XML_NAVI_ATTR_SIZE					_T("size")
#define XML_NAVI_ATTR_NAME					_T("name")
#define XML_NAVI_ATTR_FROM					_T("from")
#define XML_NAVI_ATTR_TO					_T("to")
#define XML_NAVI_ATTR_COUNT					_T("count")
#define XML_NAVI_ATTR_OPTION				_T("option")
#define XML_NAVI_ATTR_SUPPORT				_T("support")
#define XML_NAVI_ATTR_SUPPORTH				_T("supportH")
#define XML_NAVI_ATTR_SUPPORTV				_T("supportV")
#define XML_NAVI_ATTR_SEPARATE				_T("separate")
#define XML_NAVI_ATTR_UPLOAD				_T("upload")
#define XML_NAVI_ATTR_TYPE					_T("type")

#define XML_NAVI_ATTR_RGB					_T("rgb")
#define XML_NAVI_ATTR_PENSTYLE				_T("penStyle")
#define XML_NAVI_ATTR_OPACITY				_T("opacity")
#define XML_NAVI_ATTR_HALIGN				_T("halign")
#define XML_NAVI_ATTR_VALIGN				_T("valign")

#define XML_NAVI_ATTR_SERIALPORT			_T("port")
#define XML_NAVI_ATTR_BAUDRATE				_T("baudrate")
#define XML_NAVI_ATTR_DATABIT				_T("databit")
#define XML_NAVI_ATTR_PARITY				_T("parity")
#define XML_NAVI_ATTR_STOPBIT				_T("stopbit")

#define XML_NAVI_ATTR_IP					_T("ip")
#define XML_NAVI_ATTR_IPPORT				_T("port")
#define XML_NAVI_ATTR_LOCALIP				_T("local")
#define XML_NAVI_ATTR_TARGETIP				_T("target")
#define XML_NAVI_ATTR_TIMEOUT				_T("timeout")
#define XML_NAVI_ATTR_START					_T("start")
#define XML_NAVI_ATTR_ENABLE				_T("enable")

#define XML_NAVI_ATTR_ID					_T("id")
#define XML_NAVI_ATTR_INDEX					_T("index")
#define XML_NAVI_ATTR_TOTAL					_T("total")
#define XML_NAVI_ATTR_PASS					_T("pass")
#define XML_NAVI_ATTR_FAIL					_T("fail")

#define XML_NAVI_ATTR_APPFILTER_NAME		_T("filterName")
#define XML_NAVI_ATTR_APPFILTER_ROI			_T("filterRoi")
#define XML_NAVI_ATTR_APPFILTER_ROIEDGE		_T("filterRoiedge")
#define XML_NAVI_ATTR_APPFILTER_FEATURE		_T("filterFeature")
#define XML_NAVI_ATTR_APPFILTER_RESULT		_T("filterResult")
#define XML_NAVI_ATTR_APPFILTER_IMAGE		_T("filterImage")

#define XML_NAVI_ATTR_LOGGING_ENABLE		_T("enableNum")
#define XML_NAVI_ATTR_LOGGING_LIMIT			_T("limit")
#define XML_NAVI_ATTR_LOGGING_SINGLE		_T("single")
#define XML_NAVI_ATTR_LOGGING_FLAG			_T("flag")
#define XML_NAVI_ATTR_LOGGING_FORMAT		_T("format")

#define XML_NAVI_ATTR_CLIMAGETAP			_T("imgtap")
#define XML_NAVI_ATTR_CLDATABIT				_T("databit")
#define XML_NAVI_ATTR_CLCOLORTYPE			_T("colortype")
#define XML_NAVI_ATTR_CLCAMFILE				_T("camfile")
#define XML_NAVI_ATTR_CLMODEL				_T("model")
#define XML_NAVI_ATTR_CLTRIGGERMODE			_T("trigger")


// String define
#define XML_APPTYPE_NONE					_T("none")
#define XML_APPTYPE_ENHANCE_FILTER			_T("filter")
#define XML_APPTYPE_ENHANCE_THRESHOLD		_T("threshold")
#define XML_APPTYPE_ENHANCE_SEGMENTCOLOR	_T("segmentcolor")
#define XML_APPTYPE_ENHANCE_CALIBRATE		_T("calibrate")
#define XML_APPTYPE_ENHANCE_BRIGHTNESS		_T("brightness")
#define XML_APPTYPE_ENHANCE_MTIG			_T("mtig")
#define XML_APPTYPE_ENHANCE_SPLITPLANE		_T("splitplane")
#define XML_APPTYPE_MEASURE_INTENSITY		_T("intensity")
#define XML_APPTYPE_MEASURE_COUNTPIXELS		_T("countpixels")
#define XML_APPTYPE_MEASURE_MEASURECOLOR	_T("measurecolor")
#define XML_APPTYPE_MEASURE_MATCHCOLOR		_T("matchcolor")
#define XML_APPTYPE_MEASURE_CALIPER			_T("caliper")
#define XML_APPTYPE_MEASURE_GEOMETRY		_T("geometry")
#define XML_APPTYPE_LOCATE_FINDEDGE			_T("findedge")
#define XML_APPTYPE_LOCATE_LINEFITTING		_T("linefitting")
#define XML_APPTYPE_LOCATE_CIRCLEFITTING	_T("circlefitting")
#define XML_APPTYPE_LOCATE_PATTERNMATCH		_T("patternmatch")
#define XML_APPTYPE_LOCATE_SETCOORDINATE	_T("coordinate")
#define XML_APPTYPE_LOCATE_DETECTOBJECT		_T("detectobject")
#define XML_APPTYPE_LOCATE_MATCHEDGE		_T("matchedge")
#define XML_APPTYPE_IDENTIFY_BARCODE		_T("barcode")
#define XML_APPTYPE_IDENTIFY_BARCODEVER		_T("barcodeverification")
#define XML_APPTYPE_IDENTIFY_OCR			_T("ocr")
#define XML_APPTYPE_IDENTIFY_OCV			_T("ocv")
#define XML_APPTYPE_TEST					_T("test")
#define XML_APPTYPE_CAMERA_LOCALFILE		_T("localfile")
#define XML_APPTYPE_CAMERA_GIGE				_T("gige")
#define XML_APPTYPE_CAMERA_CAMERALINK		_T("cameralink")
#define XML_APPTYPE_CAMERA_USB				_T("usb")
#define XML_APPTYPE_IO_SERIAL				_T("serial")
#define XML_APPTYPE_IO_TCPIP				_T("tcpip")
#define XML_APPTYPE_ASSISTANT_HISTOGRAM		_T("histogram")
#define XML_APPTYPE_ASSISTANT_LINEPROFILE	_T("lineprofile")
#define XML_APPTYPE_ASSISTANT_MEASURE		_T("measure")
#define XML_APPTYPE_LOGIC_RESULTLOGIC		_T("resultlogic")
#define XML_APPTYPE_DIO_DEVICE				_T("deviceio")
#define XML_APPTYPE_DIO_RESULT				_T("resultio")


#define XML_ROITYPE_NONE					_T("none")
#define XML_ROITYPE_RECTANGULAR				_T("rectangular")
#define XML_ROITYPE_RECTANGULARROTATE		_T("rectangularrotate")
#define XML_ROITYPE_POLYGON					_T("polygon")
#define XML_ROITYPE_CIRCLE					_T("circle")
#define XML_ROITYPE_RING					_T("ring")
#define XML_ROITYPE_LINE					_T("line")
#define XML_ROITYPE_POINT					_T("point")
#define XML_ROITYPE_CURVE					_T("curve")
#define XML_ROITYPE_SUFFACE					_T("sufface")


#define XML_ROIFACETYPE_NORMAL				_T("normal")
#define XML_ROIFACETYPE_EDGE				_T("edge")

#define XML_ROIPOINTTYPE_START				_T("start")
#define XML_ROIPOINTTYPE_END				_T("end")
#define XML_ROIPOINTTYPE_CENTER				_T("center")
#define XML_ROIPOINTTYPE_CRITERIA			_T("criteria")

#define XML_RINGROIRANGE_RADIOUS			_T("radious")
#define XML_RINGROIRANGE_ANGLE				_T("angle")

#define XML_ROI4DIR_LEFT2RIGHT				_T("left2right")
#define XML_ROI4DIR_RIGHT2LEFT				_T("right2left")
#define XML_ROI4DIR_TOP2BOTTOM				_T("top2bottom")
#define XML_ROI4DIR_BOTTOM2TOP				_T("bottom2top")

#define XML_ROI2DIR_IN2OUT					_T("in2out")
#define XML_ROI2DIR_OUT2IN					_T("out2in")
#define XML_ROI2DIR_CCW						_T("ccw")
#define XML_ROI2DIR_CW						_T("cw")

#define XML_AUTODELETE_NONE					_T("none")
#define XML_AUTODELETE_DAILY				_T("daily")
#define XML_AUTODELETE_WEEKLY				_T("weekly")
#define XML_AUTODELETE_MONTHLY				_T("monthly")


#define XML_OUTPUTCONFIG_APPNAME			_T("appName")
#define XML_OUTPUTCONFIG_LABEL				_T("label")
#define XML_OUTPUTCONFIG_TEXT				_T("text")
#define XML_OUTPUTCONFIG_RECT				_T("rect")
#define XML_OUTPUTCONFIG_CIRCLE				_T("circle")
#define XML_OUTPUTCONFIG_LINE				_T("line")
#define XML_OUTPUTCONFIG_ARROW				_T("arrow")
#define XML_OUTPUTCONFIG_POINT				_T("point")
#define XML_OUTPUTCONFIG_IMAGE				_T("image")
#define XML_OUTPUTCONFIG_MASKIMG			_T("maksImg")
#define XML_OUTPUTCONFIG_ROI				_T("roi")
#define XML_OUTPUTCONFIG_ROIEDGGE			_T("roiEdge")
#define XML_OUTPUTCONFIG_RESULT				_T("result")
#define XML_OUTPUTCONFIG_FILTERFEATURE		_T("filterFeature")
#define XML_OUTPUTCONFIG_FILTERRESULT		_T("filterResult")

#define XML_LOGCONFIG_BMP					_T("bmp")
#define XML_LOGCONFIG_PNG					_T("png")
#define XML_LOGCONFIG_JPG					_T("jpg")

#define XML_CLGRABBER_EURESYS				_T("EURESYS")
#define XML_CLGRABBER_SILICON				_T("SILICON")
#define XML_CLGRABBER_MATROX				_T("MATROX")

#define XML_CLMODEL_CL2M					_T("LPMVC-CL2M")
#define XML_CLMODEL_CL4M					_T("LPMVC-CL4M")
#define XML_CLMODEL_CL25M					_T("LPMVC-CL25M")
#define XML_CLMODEL_CLN25M					_T("LPMVC-CL025M")

#define XML_COLOR_MONO						_T("mono")
#define XML_COLOR_COLOR						_T("color")

#define XML_COLOR_PIXELFORMAT_MONO			_T("MONO")
#define XML_COLOR_PIXELFORMAT_BAYERGR		_T("BAYER GR")
#define XML_COLOR_PIXELFORMAT_BAYERRG		_T("BAYER RG")
#define XML_COLOR_PIXELFORMAT_BAYERGB		_T("BAYER GB")
#define XML_COLOR_PIXELFORMAT_BAYERBG		_T("BAYER BG")



//
#define XML_OPTION_ROOT						_T("OPTIONROOT")
#define XML_OPTION_CAPTURE					_T("CAPTURE")
#define XML_OPTION_ALARAM					_T("ALARM")
#define XML_OPTION_ASAMPLE					_T("ASAMPLE")
#define XML_OPTION_BSAMPLE					_T("BSAMPLE")
#define XML_OPTION_SIZERANGE				_T("SIZERANGE")
#define XML_OPTION_SIZESPEC					_T("SIZESPEC")
//
#define XML_OPTION_SIZEVALID				_T("SIZEVALID")

#define XML_OPTION_MEASURE01				_T("MEASURE01")
#define XML_OPTION_MEASURE02				_T("MEASURE02")
#define XML_OPTION_MEASURE03				_T("MEASURE03")
#define XML_OPTION_MEASURE04				_T("MEASURE04")
#define XML_OPTION_MEASURE05				_T("MEASURE05")
#define XML_OPTION_MEASURE06				_T("MEASURE06")
#define XML_OPTION_MEASURE07				_T("MEASURE07")
#define XML_OPTION_MEASURE08				_T("MEASURE08")
#define XML_OPTION_MEASURE09				_T("MEASURE09")
#define XML_OPTION_MEASURE10				_T("MEASURE10")
#define XML_OPTION_MEASURE11				_T("MEASURE11")
#define XML_OPTION_MEASURE12				_T("MEASURE12")
#define XML_OPTION_MEASURE13				_T("MEASURE13")
#define XML_OPTION_MEASURE14				_T("MEASURE14")
#define XML_OPTION_MEASURE15				_T("MEASURE15")
#define XML_OPTION_MEASURE16				_T("MEASURE16")
#define XML_OPTION_MEASURE17				_T("MEASURE17")
#define XML_OPTION_MEASURE18				_T("MEASURE18")
#define XML_OPTION_MEASURE19				_T("MEASURE19")
#define XML_OPTION_MEASURE20				_T("MEASURE20")
#define XML_OPTION_MEASURE21				_T("MEASURE21")
#define XML_OPTION_MEASURE22				_T("MEASURE22")
// Version 1.3.7.5 R1 ~ R6, SS1 ~ SS3
#define XML_OPTION_MEASURE23				_T("MEASURE23")
#define XML_OPTION_MEASURE24				_T("MEASURE24")
#define XML_OPTION_MEASURE25				_T("MEASURE25")
#define XML_OPTION_MEASURE26				_T("MEASURE26")
#define XML_OPTION_MEASURE27				_T("MEASURE27")
#define XML_OPTION_MEASURE28				_T("MEASURE28")

#define XML_OPTION_INSPECTSTEP				_T("INSPECTSTEP")
// Version 1.3.6.9 Update
#define XML_OPTION_INSPECTTOSIZE			_T("INSPECTTOSIZE")
#define XML_OPTION_INSPECTTOSIZE_ALL		_T("ALLCAMERA")

#define XML_OPTION_INSPECTSTEPNAME			_T("INSPECTSTEPNAME")
#define XML_OPTION_INSPECTSTEP_FIRST		_T("FIRSTCAMERA")
#define XML_OPTION_INSPECTSTEP_SECOND		_T("SECONDCAMERA")
#define XML_OPTION_SIZENAME					_T("SIZENAME")

#define XML_OPTIONATTR_DELAY				_T("delay")
#define XML_OPTIONATTR_COUNT				_T("count")
#define XML_OPTIONATTR_ERATIO				_T("eratio")
#define XML_OPTIONATTR_CAMERA				_T("camera")
#define XML_OPTIONATTR_MIN					_T("min")
#define XML_OPTIONATTR_MAX					_T("max")
#define XML_OPTIONATTR_ODD					_T("odd")
#define XML_OPTIONATTR_EVEN					_T("even")

#define XML_OPTIONATTR_CASSETTE_COUNT		_T("cassetteCount")

#define XML_OPTIONATTR_STEP01				_T("step01")
#define XML_OPTIONATTR_STEP02				_T("step02")
#define XML_OPTIONATTR_STEP03				_T("step03")
#define XML_OPTIONATTR_STEP04				_T("step04")
#define XML_OPTIONATTR_STEP05				_T("step05")
#define XML_OPTIONATTR_STEP06				_T("step06")

#define XML_OPTIONATTR_STEP01_TITLE			_T("step01Title")
#define XML_OPTIONATTR_STEP02_TITLE			_T("step02Title")
#define XML_OPTIONATTR_STEP03_TITLE			_T("step03Title")
#define XML_OPTIONATTR_STEP04_TITLE			_T("step04Title")
#define XML_OPTIONATTR_STEP05_TITLE			_T("step05Title")
#define XML_OPTIONATTR_STEP06_TITLE			_T("step06Title")

#define XML_OPTIONATTR_SIZENAME				_T("name")

//
#define XML_INSPECT_ROOT						_T("INSPECTROOT")
#define XML_INSPECT_CAMERACHECK					_T("CAMERACHECK")
#define XML_INSPECT_STEPSIZE					_T("STEPSIZE")
#define XML_INSPECT_STEPSTAIN					_T("STEPSTAIN")
#define XML_INSPECT_STEPDIFFER					_T("STEPDIFFER")
#define XML_INSPECT_STEPBUBBLE					_T("STEPBUBBLE")
#define XML_INSPECT_STEPSCRATCH					_T("STEPSCRATCH")
#define XML_INSPECT_STEPSTAMP					_T("STEPSTAMP")
#define XML_INSPECT_STEPSIZESECOND				_T("STEPSIZESECOND")
#define XML_INSPECT_CALC						_T("CALC")

#define XML_INSPECT_SIZECALIBRATE				_T("SIZECALIBRATE")
#define XML_INSPECT_CALIBRATEPATHLIST			_T("CALIBRATEPATHLIST")
#define XML_INSPECT_CALIBRATEPATH				_T("CALIBRATEPATH")
#define XML_INSPECT_CALIBRATEPARAM				_T("CALIBRATEPARAM")
#define XML_INSPECT_SIZEGAIN					_T("SIZEGAIN")
#define XML_INSPECT_SIZEROILIST					_T("SIZEROILIST")
#define XML_INSPECT_SIZEROI						_T("SIZEROI")
#define XML_INSPECT_SIZEPOINT					_T("SIZEPOINT")
#define XML_INSPECT_SIZESAMPLE					_T("SIZESAMPLE")
#define XML_INSPECT_SIZEPARAM					_T("SIZEPARAM")

#define XML_INSPECT_STEPSTROBELIST				_T("STEPSTROBELIST")
#define XML_INSPECT_STEPSTROBE					_T("STEPSTROBE")

#define XML_INSPECT_RECTROI						_T("RECTROI")
#define XML_INSPECT_PARAM_MARS					_T("PARAMMARS")
#define XML_INSPECT_PARAM_CALIB					_T("PARAMCALIB")
#define XML_INSPECT_PARAM_JUDGMENT				_T("PARAMJUDGMENT")
// Version 1.3.8.1 Image Save & Compress
#define XML_INSPECT_PARAM_IMAGE					_T("PARAIMAGE")

#define XML_INSPECTATTR_CAMERANUM				_T("cameraNum")
#define XML_INSPECTATTR_STEPENABLE				_T("stepEnable")
#define XML_INSPECTATTR_STROBETYPE				_T("strobeType")
#define XML_INSPECTATTR_STROBEBRIGHT			_T("strobeBright")
#define XML_INSPECTATTR_IMAGEPATH				_T("calibratePath")
#define XML_INSPECTATTR_LISTCOUNT				_T("calibrateCount")
#define XML_INSPECTATTR_REFIDX					_T("calibrateRefIdx")
#define XML_INSPECTATTR_ROW						_T("calibrateRow")
#define XML_INSPECTATTR_COL						_T("calibrateCol")
#define XML_INSPECTATTR_SPACING					_T("calibrateSpacing")
#define XML_INSPECTATTR_UNI						_T("calibrateUni")

#define XML_INSPECTATTR_CALIBRATE_METHOD		_T("calibrateMethod")
#define XML_INSPECTATTR_CALIBRATE_IMAGEWIDTH	_T("calibrateImageWidth")
#define XML_INSPECTATTR_CALIBRATE_IMAGEHEIGHT	_T("calibrateImageHeight")
#define XML_INSPECTATTR_CALIBRATE_WIDTH			_T("calibrateWidth")
#define XML_INSPECTATTR_CALIBRATE_HEIGHT		_T("calibrateHeight")
#define XML_INSPECTATTR_CALIBRATE_PIXELUNIT		_T("calibratePixelUnit")

#define XML_INSPECTATTR_SIZEGAIN_D				_T("sizegainD")
#define XML_INSPECTATTR_SIZEGAIN_L				_T("sizegainL")
#define XML_INSPECTATTR_SIZEGAIN_W				_T("sizegainW")
#define XML_INSPECTATTR_SIZEGAIN_I1				_T("sizegainI1")
#define XML_INSPECTATTR_SIZEGAIN_I2				_T("sizegainI2")
#define XML_INSPECTATTR_SIZEGAIN_I3				_T("sizegainI3")
#define XML_INSPECTATTR_SIZEGAIN_M1				_T("sizegainM1")
#define XML_INSPECTATTR_SIZEGAIN_M2				_T("sizegainM2")
#define XML_INSPECTATTR_SIZEGAIN_S1				_T("sizegainS1")
#define XML_INSPECTATTR_SIZEGAIN_S2				_T("sizegainS2")
#define XML_INSPECTATTR_SIZEGAIN_S3				_T("sizegainS3")
#define XML_INSPECTATTR_SIZEGAIN_S4				_T("sizegainS4")
#define XML_INSPECTATTR_SIZEGAIN_S5				_T("sizegainS5")
#define XML_INSPECTATTR_SIZEGAIN_X1				_T("sizegainX1")
#define XML_INSPECTATTR_SIZEGAIN_X2				_T("sizegainX2")
#define XML_INSPECTATTR_SIZEGAIN_R1				_T("sizegainR1")
#define XML_INSPECTATTR_SIZEGAIN_R2				_T("sizegainR2")
#define XML_INSPECTATTR_SIZEGAIN_R3				_T("sizegainR3")
#define XML_INSPECTATTR_SIZEGAIN_R4				_T("sizegainR4")
// Version 1.3.7.5 R1 ~ R6, SS1 ~ SS3
#define XML_INSPECTATTR_SIZEGAIN_R5				_T("sizegainR5")
#define XML_INSPECTATTR_SIZEGAIN_R6				_T("sizegainR6")
#define XML_INSPECTATTR_SIZEGAIN_SS1			_T("sizegainSS1")
#define XML_INSPECTATTR_SIZEGAIN_SS2			_T("sizegainSS2")
#define XML_INSPECTATTR_SIZEGAIN_SS3			_T("sizegainSS3")

#define XML_INSPECTATTR_WIDTH					_T("sampleWidth")
#define XML_INSPECTATTR_HEIGHT					_T("sampleHeight")
#define XML_INSPECTATTR_ANGLE					_T("sampleAngle")
#define XML_INSPECTATTR_ANGLE_CRITERIA			_T("sampleAngleCriteria")
#define XML_INSPECTATTR_POINTTYPE				_T("pointType")
#define XML_INSPECTATTR_POINTX					_T("pointX")
#define XML_INSPECTATTR_POINTY					_T("pointY")
#define XML_INSPECTATTR_SAMPLETYPE				_T("sampleType")
#define XML_INSPECTATTR_SAMPLEDIRECTION			_T("sampleDirection")
#define XML_INSPECTATTR_SAMPLEPOLAR				_T("samplePolar")
#define XML_INSPECTATTR_SAMPLELOOKFOR			_T("samplelookFor")
#define XML_INSPECTATTR_SAMPLESTRTHRESHOLD		_T("sampleStrThreshold")
#define XML_INSPECTATTR_SAMPLESAMPLING			_T("sampleSampling")
#define XML_INSPECTATTR_SAMPLEKERNELSIZE		_T("sampleKernelSize")
#define XML_INSPECTATTR_SAMPLESEARCHANGLE		_T("sampleSearchAngle")
#define XML_INSPECTATTR_SAMPLEMINANGLE			_T("sampleMinAngle")
#define XML_INSPECTATTR_SAMPLEMAXANGLE			_T("sampleMaxAngle")
#define XML_INSPECTATTR_SAMPLEDISTTHRESHOLD		_T("sampleDistThreshold")

#define XML_INSPECTATTR_RECT_LEFT				_T("rectLeft")
#define XML_INSPECTATTR_RECT_TOP				_T("rectTop")
#define XML_INSPECTATTR_RECT_RIGHT				_T("rectRight")
#define XML_INSPECTATTR_RECT_BOTTOM				_T("rectBottom")

#define XML_INSPECTATTR_MARSPARAM_PROBTHRES			_T("probThres")
#define XML_INSPECTATTR_MARSPARAM_BLOBSIZETHRES		_T("blobSizeThres")

#define XML_INSPECTATTR_CALIBPARAM_PIXEL2REAL		_T("pixel2real")
#define XML_INSPECTATTR_CALIBPARAM_REAL2PIXEL		_T("real2pixel")

#define XML_INSPECTATTR_JUDGPARAM_FAULTNUM			_T("faultNum")
#define XML_INSPECTATTR_JUDGBPARAM_FAULTSIZE		_T("faultSize")
// Version 1.3.8.1
#define XML_INSPECTATTR_IMAGEPARAM_WRITE			_T("imageWrite")
#define XML_INSPECTATTR_IMAGEPARAM_COMPRESS			_T("imageCompress")



#define XML_INSPECTATTR_VALUE_STORBE_COXIAL		_T("coxial")
#define XML_INSPECTATTR_VALUE_STORBE_RING		_T("ring")
#define XML_INSPECTATTR_VALUE_STORBE_BAR		_T("bar")
#define XML_INSPECTATTR_VALUE_STORBE_OFF		_T("off")

#define XML_INSPECTATTR_VALUE_POINT_CENTER		_T("center")
#define XML_INSPECTATTR_VALUE_POINT_CRITERIA	_T("criteria")
#define XML_INSPECTATTR_VALUE_SAMPLE_A			_T("a")
#define XML_INSPECTATTR_VALUE_SAMPLE_B			_T("b")



//
#define MAX_XML_NAME_LEN		128


typedef enum
{
	TYPE_XML_VALUE_NONE,

	TYPE_XML_VALUE_STRING,
	TYPE_XML_VALUE_SIGNED,
	TYPE_XML_VALUE_UNSIGNED,
	TYPE_XML_VALUE_DOUBLE,
	TYPE_XML_VALUE_HEX,			// Hex string
	TYPE_XML_VALUE_BINARY,

} TYPE_XML_VALUE;