#pragma once

// GigE Function
#define LP_GIGE_VID_BASE                          0x80000000
#define LP_GIGE_VID_GIGE_PART                     0x00000000
#define LP_GIGE_VID_FPGA_PART                     0x00010000
#define LP_GIGE_VID_SENSOR_PART                   0x00020000
#define LP_GIGE_VID_ITEM_BITF                     0x000000FF

#define REG_FUNC_VID_GROUP(x)                     ((0x00030000&x)>>16) // 0: GIGE, 1: FPGA, 2:SENSOR


// GigE-Part	
#define	LP_GIGE_RO_GEN_GIGEVER                    (LP_GIGE_VID_BASE | LP_GIGE_VID_GIGE_PART | 0x001)
#define	LP_GIGE_RO_GEN_DEVMODE                    (LP_GIGE_VID_BASE | LP_GIGE_VID_GIGE_PART | 0x002)
#define	LP_GIGE_RO_GEN_DEVMAC_H                   (LP_GIGE_VID_BASE | LP_GIGE_VID_GIGE_PART | 0x003)
#define	LP_GIGE_RO_GEN_DEVMAC_L                   (LP_GIGE_VID_BASE | LP_GIGE_VID_GIGE_PART | 0x004)
#define	LP_GIGE_RO_GEN_CUR_IP_ADDR                (LP_GIGE_VID_BASE | LP_GIGE_VID_GIGE_PART | 0x005)
#define	LP_GIGE_RO_GEN_CUR_SUBNET                 (LP_GIGE_VID_BASE | LP_GIGE_VID_GIGE_PART | 0x006)
#define	LP_GIGE_RO_GEN_CUR_GATEWAY                (LP_GIGE_VID_BASE | LP_GIGE_VID_GIGE_PART | 0x007)
#define	LP_GIGE_RW_GEN_PERSIS_IP                  (LP_GIGE_VID_BASE | LP_GIGE_VID_GIGE_PART | 0x008)
#define	LP_GIGE_RW_GEN_PERSIS_SUBNET              (LP_GIGE_VID_BASE | LP_GIGE_VID_GIGE_PART | 0x009)
#define	LP_GIGE_RW_GEN_PERSIS_GATEWAY             (LP_GIGE_VID_BASE | LP_GIGE_VID_GIGE_PART | 0x010)
#define	LP_GIGE_RW_GEN_HEARTBEAT_TO               (LP_GIGE_VID_BASE | LP_GIGE_VID_GIGE_PART | 0x011)
#define	LP_GIGE_RW_DEST_PORT                      (LP_GIGE_VID_BASE | LP_GIGE_VID_GIGE_PART | 0x012)
#define	LP_GIGE_RW_MTU                            (LP_GIGE_VID_BASE | LP_GIGE_VID_GIGE_PART | 0x013)
#define	LP_GIGE_RW_DEST_IP                        (LP_GIGE_VID_BASE | LP_GIGE_VID_GIGE_PART | 0x014)
#define LP_GIGE_REG_GIGE_ITEMS                    (LP_GIGE_RW_DEST_IP&0x000000FF) // last item num & 0x000000FF
		
// FPGA-Part	
#define	LP_GIGE_RW_OPMODE                         (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x001)
#define	LP_GIGE_RW_FUNCMODE                       (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x002)
#define	LP_GIGE_RW_IMG_WIDTH                      (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x003)
#define	LP_GIGE_RW_IMG_HEIGHT                     (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x004)
#define	LP_GIGE_RW_PIXELFORMAT                    (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x005)
#define	LP_GIGE_RO_FPGA_VERSION                   (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x006)
#define	LP_GIGE_WO_SWRESET                        (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x007)
#define	LP_GIGE_RW_TRIG_SRC                       (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x008)
#define	LP_GIGE_RW_TRIG_EN                        (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x009)
#define	LP_GIGE_RW_TRIG_POL                       (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x00A)
#define	LP_GIGE_RW_TRIG_DELAY                     (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x00B)
#define	LP_GIGE_RW_TRIG_WIDTH                     (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x00C)
#define	LP_GIGE_RW_STROBE_EN                      (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x00D)
#define	LP_GIGE_RW_STROBE_TYPE                    (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x00E)
#define	LP_GIGE_RW_STROBE_POL                     (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x00F)
#define	LP_GIGE_RW_STROBE_DELAY                   (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x010)
#define	LP_GIGE_RW_STROBE_WIDTH                   (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x011)
#define	LP_GIGE_WO_ERASE_USERSET                  (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x012)
#define	LP_GIGE_WO_SAVE_USERSET                   (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x013)
#define	LP_GIGE_WO_LOAD_USERSET                   (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x014)
#define	LP_GIGE_WO_START_USERSET                  (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x015)
#define	LP_GIGE_RW_NUM_USERSET                    (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x016)
#define	LP_GIGE_RO_IMG_MAXWIDTH                   (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x017)
#define	LP_GIGE_RO_IMG_MAXHEIGHT                  (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x018)
#define	LP_GIGE_RW_IMG_XOFFSET                    (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x019)
#define	LP_GIGE_RW_IMG_YOFFSET                    (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x01A)
#define	LP_GIGE_RW_COLOR_ENHANCEMENT_DPC_EN       (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x01B)
#define	LP_GIGE_RW_COLOR_ENHANCEMENT_LPF_EN       (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x01C)
#define	LP_GIGE_RW_COLOR_ENHANCEMENT_CM_EN        (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x01D)
#define	LP_GIGE_RW_COLOR_ENHANCEMENT_GM_EN        (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x01E)
#define	LP_GIGE_RW_GAMMA_TABLE_NUM                (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x01F)
#define	LP_GIGE_RW_AE_EN                          (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x020)
#define	LP_GIGE_RW_HW_AWB_EN                      (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x021)
#define	LP_GIGE_RW_AE_TARGET_VL                   (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x022)
#define LP_GIGE_RW_AE_INIT_TIME_VL                (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x023)
#define LP_GIGE_RW_FRAME_RATE_EN                  (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x024)
#define LP_GIGE_RW_FRAME_RATE                     (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x025)
#define LP_GIGE_RW_MAX_FRAME_RATE                 (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x026)
#define LP_GIGE_RW_COLOR_ENHANCEMENT_PRNU_EN      (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x027)
#define LP_GIGE_RW_COLOR_ENHANCEMENT_LUT_EN       (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x028)
#define LP_GIGE_RW_COLOR_LUT_TABLE_NUM            (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x029)

#define LP_GIGE_RW_CALIBRATION_EN                 (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x02A)
#define LP_GIGE_RW_CALIBRATION                    (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x02B)

#define LP_GIGE_RW_TEST_PATTERN_EN                (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x02C)
#define LP_GIGE_RW_TEST_PATTERN_NUM               (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x02D)

// ADD New Functions 201512
#define LP_GIGE_RW_DDR_RESET                      (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x02E)
#define LP_GIGE_RW_PACKET_DELAY                   (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x02F)
#define LP_GIGE_RW_FRAME_DELAY                    (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x030)
#define	LP_GIGE_RW_COLOR_ENHANCEMENT_DPC_VIEW     (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x031)

#define LP_GIGE_RW_DPC_THRESHOLD                  (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x032)
#define	LP_GIGE_RW_DEGLITCH_TIME                  (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x033)

#define	LP_GIGE_RW_AE_TARGET_MIN_VL               (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x034)
#define	LP_GIGE_RW_AE_TARGET_MAX_VL               (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x035)

#define	LP_GIGE_RO_XML_VERSION                    (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x036)
#define	LP_GIGE_RO_CAMINIT_VERSION                (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x037)

// Register 추가시 LP_GIGE_RO_FLADDRESS_USERSET 항목 위로 추가
#define LP_GIGE_RO_FLADDRESS_USERSET              (LP_GIGE_VID_BASE | LP_GIGE_VID_FPGA_PART | 0x038)

#define LP_GIGE_REG_FPGA_ITEMS                    (LP_GIGE_RO_FLADDRESS_USERSET&0x000000FF) // last item num & 0x000000FF
		
// Sensor-Part	
#define	LP_GIGE_RW_SS_BIN_MODE                    (LP_GIGE_VID_BASE | LP_GIGE_VID_SENSOR_PART | 0x001)
#define	LP_GIGE_RW_SS_MIRROR_COL                  (LP_GIGE_VID_BASE | LP_GIGE_VID_SENSOR_PART | 0x002)
#define	LP_GIGE_RW_SS_MIRROR_ROW                  (LP_GIGE_VID_BASE | LP_GIGE_VID_SENSOR_PART | 0x003)
#define	LP_GIGE_RW_SS_GAIN_GLOBAL                 (LP_GIGE_VID_BASE | LP_GIGE_VID_SENSOR_PART | 0x004)
#define	LP_GIGE_RW_SS_GAIN_ANALOG                 (LP_GIGE_VID_BASE | LP_GIGE_VID_SENSOR_PART | 0x005)

#define	LP_GIGE_RW_SS_EXPOSURE_TI                 (LP_GIGE_VID_BASE | LP_GIGE_VID_SENSOR_PART | 0x006)
#define	LP_GIGE_RW_SS_GAIN_GREEN1                 (LP_GIGE_VID_BASE | LP_GIGE_VID_SENSOR_PART | 0x007)
#define	LP_GIGE_RW_SS_GAIN_BLUE                   (LP_GIGE_VID_BASE | LP_GIGE_VID_SENSOR_PART | 0x008)
#define	LP_GIGE_RW_SS_GAIN_RED                    (LP_GIGE_VID_BASE | LP_GIGE_VID_SENSOR_PART | 0x009)
#define	LP_GIGE_RW_SS_GAIN_GREEN2                 (LP_GIGE_VID_BASE | LP_GIGE_VID_SENSOR_PART | 0x00A)
#define LP_GIGE_RW_SS_XSTART                      (LP_GIGE_VID_BASE | LP_GIGE_VID_SENSOR_PART | 0x00B)
#define LP_GIGE_RW_SS_YSTART                      (LP_GIGE_VID_BASE | LP_GIGE_VID_SENSOR_PART | 0x00C)
#define LP_GIGE_RW_SS_HBLANK                      (LP_GIGE_VID_BASE | LP_GIGE_VID_SENSOR_PART | 0x00D)
#define LP_GIGE_RW_SS_VBLANK                      (LP_GIGE_VID_BASE | LP_GIGE_VID_SENSOR_PART | 0x00E)
#define LP_GIGE_RW_SS_AGC                         (LP_GIGE_VID_BASE | LP_GIGE_VID_SENSOR_PART | 0x00F)
#define LP_GIGE_RW_SS_AEC                         (LP_GIGE_VID_BASE | LP_GIGE_VID_SENSOR_PART | 0x010)
#define LP_GIGE_REG_SENSOR_ITEMS                  (LP_GIGE_RW_SS_AEC&0x000000FF) // last item num & 0x000000FF